//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buyutec.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAltSurec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAltSurec()
        {
            this.tblKullaniciAltSurecs = new HashSet<tblKullaniciAltSurec>();
        }
    
        public int altSurecId { get; set; }
        public string altSurecAdi { get; set; }
        public Nullable<System.DateTime> baslangicTarihi { get; set; }
        public Nullable<System.DateTime> bitisTarihi { get; set; }
        public Nullable<int> bitirmeOrani { get; set; }
        public Nullable<int> durumId { get; set; }
        public Nullable<int> oncelikId { get; set; }
        public Nullable<int> surecId { get; set; }
        public string aciklama { get; set; }
    
        public virtual tblDurum tblDurum { get; set; }
        public virtual tblOncelik tblOncelik { get; set; }
        public virtual tblSurec tblSurec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKullaniciAltSurec> tblKullaniciAltSurecs { get; set; }
    }
}
