//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buyutec.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuyutecDBEntities : DbContext
    {
        public BuyutecDBEntities()
            : base("name=BuyutecDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAltSurec> tblAltSurecs { get; set; }
        public virtual DbSet<tblDurum> tblDurums { get; set; }
        public virtual DbSet<tblKullanici> tblKullanicis { get; set; }
        public virtual DbSet<tblKullaniciAltSurec> tblKullaniciAltSurecs { get; set; }
        public virtual DbSet<tblKullaniciProje> tblKullaniciProjes { get; set; }
        public virtual DbSet<tblKullaniciRol> tblKullaniciRols { get; set; }
        public virtual DbSet<tblKullaniciSurec> tblKullaniciSurecs { get; set; }
        public virtual DbSet<tblOncelik> tblOnceliks { get; set; }
        public virtual DbSet<tblProje> tblProjes { get; set; }
        public virtual DbSet<tblRol> tblRols { get; set; }
        public virtual DbSet<tblSurec> tblSurecs { get; set; }
    }
}
