//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buyutec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullaniciAltSurec
    {
        public int id { get; set; }
        public int kullaniciId { get; set; }
        public int altSurecId { get; set; }
    
        public virtual tblAltSurec tblAltSurec { get; set; }
        public virtual tblKullanici tblKullanici { get; set; }
    }
}
